### ISSUE TITLE
Problem with compiling conditionals with FITC?

### ISSUE THREAD

**Issue by jugeeya** [Sammi-Husky/Sm4sh-Tools#66] opened 2017-07-15 19:19 UTC
When compiling the TRUE(Unknown={}) or FALSE(Unknown={}), it seems that the numbers output are never what I expect they should be. Below is the file before compilation on the left, and the result of the compilation in Sm4shcommand (the result is also the same when decompiling the compilation with FITD again). What should be 0x12 and 0x10 have turned into 0x152 and 0x156; further, the same thing happens for game.bin even though I have not changed it (the values go from 0x88 and 0x86 to 0x86 and 0x86). Am I missing something?

![image](https://user-images.githubusercontent.com/15069495/28242079-f7c03b22-6956-11e7-9070-0e317acf5b94.png)

**Comment by Sammi-Husky** [comment] 2017-07-15 22:22
The TRUE/FALSE parameters are the size of the block of commands. So the number represents the total size of all commands inside of it (counting parameters).

As an aside, the conditionals don't work exactly how i'd like them to yet and may be slightly broken recompiling, since i think the auto-calculation of those numbers is off

**Comment by jugeeya** [comment] 2017-07-15 23:56
Are you sure that is the case? I know that's how it works for Goto statements in loops, but here it doesn't seem to be so. This is the original code for Cloud's side b-1 effects:

TRUE(Unknown=0x12){
		    EFFECT_FOLLOW_NO_STOP_WITH_HANDLE(unknown=0x3370009, unknown=0x0, unknown=0x0, unknown=0x41200000, unknown=0x41880000, unknown=0x0, unknown=0x42C80000, unknown=0x0, unknown=0x3F800000, unknown=0x1, unknown=0x0, unknown=0x0, unknown=0x10000085)
		}
		FALSE(Unknown=0x10){
		    EFFECT_FOLLOW_NO_STOP_WITH_HANDLE(unknown=0x3370005, unknown=0x0, unknown=0x0, unknown=0x41200000, unknown=0x41880000, unknown=0x0, unknown=0xC2C80000, unknown=0x0, unknown=0x3F800000, unknown=0x1, unknown=0x0, unknown=0x0, unknown=0x10000085)
		}

Not only are the conditional parameters different from one another (always by 2 in original code), neither is equal to the "total size" thing, it seems.

**Comment by Sammi-Husky** [comment] 2017-07-16 00:12
0x12 = 18, counting the TRUE command and it's parameter the block is 16, but the FALSE command is also technically part of the block as well, adding 2 to make it 18. The reason it isn't in brackets even though it's counted is because i intentionally break FALSE blocks out of enclosing TRUE blocks so that it makes more sense.

But functionally, the FALSE is also counted. Because technically the TRUE parameter is an OFFSET to the next command to execute if the TRUE is false. So param 0x12 is basically a jump to the FALSE.

**Comment by Sammi-Husky** [comment] 2017-07-16 00:12
which is why the FALSE is 2 less than the TRUE, since it doesn't have a FALSE counted in it

**Comment by jugeeya** [comment] 2017-07-16 01:50
Oh I see! I didn't count the command itself! Thank you, that makes so much sense. It's good to finally know how it works. I was wondering why no matter what number I put in there, it would change no matter what, and it's because FITC simply reads the body to find out what number to put as the conditional parameter.

Still, I don't know why the compilation doesn't allow the conditional to actually function in game. Hopefully I figure it out soon. For example, when I change Cloud's side b, since the conditional is for the direction he is facing, it only works for one of the conditionals, whichever means that he is facing left. This occurs whether I apply my changes or even if I just decompile and recompile Cloud without any changes. I will continue to test.

**Comment by Sammi-Husky** [comment] 2017-07-16 03:00
I'm fairly certain the issue with the compilation is just due to TRUE/FALSE blocks auto calculation being wrong. The TRUE circumstance will work but the FALSE never will because the parameter on TRUE isn't calculating for it to jump to AFTER the FALSE. I'll try to fix this in the next couple days

**Comment by jugeeya** [comment] 2017-07-16 03:07
Yes that seems to be the case. In fact, the modpack I'm working on has that exact problem that you describe, only going into the TRUE blocks. Therefore Robin Levin sword works but bronze doesn't, Ryu non-true inputs work but true ones don't, Cloud side b as mentioned, etc... Thank you so much!

**Comment by Sammi-Husky** [comment] 2017-07-16 09:59
This is fixed in SM4SHCommand as of that commit. I will add the relevant fix to FITX's compiler as well as soon as i can.

**Comment by jugeeya** [comment] 2017-07-16 17:02
I can confirm that it works in Sm4shcommand now! :D I recompiled my edits and simply resaved the conditional moves in Sm4shcommand to test lol. Thanks a ton!
![cloudsidebright](https://user-images.githubusercontent.com/15069495/28249606-defbd210-6a0d-11e7-8693-9ed1a0045de5.png)
![cloudsidebleft](https://user-images.githubusercontent.com/15069495/28249607-df01c71a-6a0d-11e7-8e6c-036f5a24b3bb.png)

**Comment by Sammi-Husky** [comment] 2017-07-16 23:20
Fixed and added to the FITC compiler in eac12a8. If anything else gets broken feel free to let me know

**Comment by jugeeya** [comment] 2017-07-18 05:22
The FITC compiler works! Although it seems that the auto-calculation only fuctions for the TRUE blocks. I've accounted for this and calculated the FALSE block values myself in my script and it works perfectly, however. Thank you so much!

**Comment by Sammi-Husky** [comment] 2017-07-18 23:24
Really? When testing before push i was able to get it to consistantly rebuild complex scripts like bayo and ryu perfectly with no changes. Can you provide an example of where it isnt working?

**Comment by jugeeya** [comment] 2017-07-19 15:40
Oh I'm sorry, I must've been using an older version of Sm4shcommand or something. Now I have no issue.

**Comment by jugeeya** [comment] 2017-07-19 16:00
Oh wait no, it does seem to be the case. Look at this pair of TRUE and FALSE in Robin's Fsmash: I left it as 0x3, and it remains as 0x3 after compilation whereas it should be 0x6. 

![image](https://user-images.githubusercontent.com/15069495/28377097-a21de4f0-6c60-11e7-9a7c-bff2a8f40390.png)

This is one of the more obvious ones in Cloud's side b (where the calculated value should be more than the one I had, as the functions that should be in the body get taken outside):
![image](https://user-images.githubusercontent.com/15069495/28377298-2fb0b716-6c61-11e7-9e0f-0914b97b7e47.png)

**Comment by Sammi-Husky** [comment] 2017-07-19 23:59
Interesting. This may have been caused by some later changes i made to fix #67

**Comment by Sammi-Husky** [comment] 2017-07-20 00:55
Pushed a few commits that might fix this, could you try again with latest commit build?

**Comment by jugeeya** [comment] 2017-07-20 01:36
Sounds good. I will check right now.

**Comment by jugeeya** [comment] 2017-07-20 02:14
Seems to be working, I can't be sure though. What I did was I used some wrong values for all of them, and the majority seem to have been calculated correctly, the exception being the outermost FALSE which remains the same (again, left is before compilation, right is after). Works in game as far as I can tell.

![image](https://user-images.githubusercontent.com/15069495/28397452-70d8ffb4-6cb6-11e7-834c-3d3aa07077a9.png)

**Comment by Sammi-Husky** [comment] 2017-07-20 02:35
Does it compile unchanged scripts back to original? I.e decompile ryu uspecial, recompile unchanged, check if it's same as original

**Comment by jugeeya** [comment] 2017-07-20 02:38
Yes it does.

**Comment by Sammi-Husky** [comment] 2017-07-21 21:28
Awesome, everything seems to be in order then. I'll go ahead and close this issue now 👍

**Closed as completed by Sammi-Husky** 2017-07-21 21:28 UTC
Labels: bug, core, FITX
